jobs:
  - job: 'build_docs'
    displayName: 'Build Docs'
    strategy:
      matrix:
        'java-17':
          image: 'Ubuntu-22.04'
          jdk_version: '17'
    # Strategy for the job
    # Set timeout for jobs
    timeoutInMinutes: 60
    # Base system
    pool:
      vmImage: $(image)
    # Variables
    variables:
      MVN_CACHE_FOLDER: $(HOME)/.m2/repository
      MVN_ARGS: '-e -V -B'
    # Pipeline steps
    steps:
      # Get cached Maven repository
      - template: "../steps/maven_cache.yaml"
      - template: '../steps/prerequisites/install_java.yaml'
        parameters:
          JDK_VERSION: $(jdk_version)
      - template: '../steps/prerequisites/install_asciidoc.yaml'
      - bash: "make docu_html docu_htmlnoheader"
        displayName: "Build docs"
        env:
          MVN_ARGS: "-e -V -B"
      # We have to TAR the target directory to maintain the permissions of
      # the files which would otherwise change when downloading the artifact
      - bash: tar -cvpf documentation.tar ./documentation
        displayName: "Tar the documentation directory"
      - publish: $(System.DefaultWorkingDirectory)/documentation.tar
        artifact: Documentation
        displayName: "Store the documentation tar"