jobs:
  - job: 'build_container'
    displayName: 'Build'
    # Set timeout for jobs
    timeoutInMinutes: 60
    # Base system
    pool:
      vmImage: 'Ubuntu-20.04'
    # Pipeline steps
    steps:
      - template: '../steps/setup_docker.yaml'
      - task: DownloadPipelineArtifact@2
        inputs:
          source: '${{ parameters.artifactSource }}'
          artifact: Binary
          path: $(System.DefaultWorkingDirectory)/
          project: '${{ parameters.artifactProject }}'
          pipeline: '${{ parameters.artifactPipeline }}'
          runVersion: '${{ parameters.artifactRunVersion }}'
          runId: '${{ parameters.artifactRunId }}'
      - bash: tar -xvf target.tar
        displayName: "Untar the target directory"
      - bash: ".azure/scripts/container-build.sh"
        env:
          BUILD_REASON: $(Build.Reason)
          BRANCH: $(Build.SourceBranch)
          DOCKER_REGISTRY: "quay.io"
          DOCKER_ORG: "strimzi"
        displayName: "Build container"
      - publish: $(System.DefaultWorkingDirectory)/kafka-bridge.tar.gz
        artifact: Container