jobs:
  - job: 'deploy_java'
    displayName: 'Deploy Java'
    # Set timeout for jobs
    timeoutInMinutes: 60
    # Base system
    pool:
      vmImage: 'Ubuntu-22.04'
    # Pipeline steps
    steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          source: '${{ parameters.artifactSource }}'
          artifact: Binary
          path: $(System.DefaultWorkingDirectory)/
          project: '${{ parameters.artifactProject }}'
          pipeline: '${{ parameters.artifactPipeline }}'
          runVersion: '${{ parameters.artifactRunVersion }}'
          runId: '${{ parameters.artifactRunId }}'
      - bash: tar -xvf target.tar
        displayName: "Untar the target directory"
      - bash: "./.azure/scripts/push-to-nexus.sh"
        env:
          BUILD_REASON: $(Build.Reason)
          BRANCH: $(Build.SourceBranch)
          GPG_PASSPHRASE: $(GPG_PASSPHRASE)
          GPG_SIGNING_KEY: $(GPG_SIGNING_KEY)
          NEXUS_USERNAME: $(NEXUS_USERNAME)
          NEXUS_PASSWORD: $(NEXUS_PASSWORD)
        displayName: "Deploy Java artifacts"