jobs:
  - job: 'push_container'
    displayName: 'Tag & Push'
    # Set timeout for jobs
    timeoutInMinutes: 60
    # Base system
    pool:
      vmImage: 'Ubuntu-20.04'
    # Pipeline steps
    steps:
      - template: '../steps/setup_docker.yaml'
      - task: DownloadPipelineArtifact@2
        inputs:
          source: '${{ parameters.artifactSource }}'
          artifact: Container
          path: $(System.DefaultWorkingDirectory)
          project: '${{ parameters.artifactProject }}'
          pipeline: '${{ parameters.artifactPipeline }}'
          runVersion: '${{ parameters.artifactRunVersion }}'
          runId: '${{ parameters.artifactRunId }}'
      - bash: ".azure/scripts/container-push.sh"
        env:
          BUILD_REASON: $(Build.Reason)
          BRANCH: $(Build.SourceBranch)
          DOCKER_USER: $(QUAY_USER)
          DOCKER_PASS: $(QUAY_PASS)
          DOCKER_REGISTRY: "quay.io"
          DOCKER_ORG: "strimzi"
          DOCKER_TAG: '${{ parameters.dockerTag }}'
        displayName: "Tag & Push container"
