jobs:
  - job: 'release_artifacts'
    displayName: 'Prepare and release artifacts'
    # Set timeout for jobs
    timeoutInMinutes: 60
    # Base system
    pool:
      vmImage: 'Ubuntu-22.04'
    # Pipeline steps
    steps:
      # Install Prerequisites
      - template: '../steps/prerequisites/install_java.yaml'

      # Change the release version
      - bash: "mvn versions:set -DnewVersion=$(shell echo $(RELEASE_VERSION) | tr a-z A-Z)"
        displayName: "Configure release version to ${{ parameters.releaseVersion }}"
        env:
          RELEASE_VERSION: '${{ parameters.releaseVersion }}'

      - bash: "mvn install -DskipTests"
        displayName: "Build Java"

      # Deploy to Central
      - bash: "./.azure/scripts/push-to-central.sh"
        env:
          BUILD_REASON: $(Build.Reason)
          BRANCH: $(Build.SourceBranch)
          GPG_PASSPHRASE: $(GPG_PASSPHRASE)
          GPG_SIGNING_KEY: $(GPG_SIGNING_KEY)
          CENTRAL_USERNAME: $(CENTRAL_USERNAME)
          CENTRAL_PASSWORD: $(CENTRAL_PASSWORD)
          MVN_ARGS: "-e -V -B"
        displayName: "Deploy Java artifacts"