# Triggers
trigger:
  branches:
    include:
      - 'main'
      - 'release-*'
  tags:
    include:
      - '*'
pr:
  autoCancel: true
  branches:
    include:
      - '*'
# Jobs
jobs:
  - job: 'build_and_test'
    displayName: 'Build & Test'
    # Strategy for the job
    strategy:
      matrix:
        'java-8':
          image: 'Ubuntu-18.04'
          jdk_version: '1.8'
          jdk_path: '/usr/lib/jvm/java-8-openjdk-amd64'
        'java-11':
          image: 'Ubuntu-18.04'
          jdk_version: '11'
          jdk_path: '/usr/lib/jvm/java-11-openjdk-amd64'
    # Set timeout for jobs
    timeoutInMinutes: 60
    # Base system
    pool:
      vmImage: $(image)
    # Variables
    variables:
      MVN_CACHE_FOLDER: $(HOME)/.m2/repository
      MVN_ARGS: '-e -V -B'
    # Pipeline steps
    steps:
      - task: Cache@2
        inputs:
          key: 'mvn-m2-cache | $(System.JobName)'
          path: "$(MVN_CACHE_FOLDER)"
        displayName: Maven cache
      - template: 'templates/setup_java.yaml'
        parameters:
          JDK_PATH: $(jdk_path)
          JDK_VERSION: $(jdk_version)
      - task: UseRubyVersion@0
        inputs:
          versionSpec: '>= 2.4'
          addToPath: true
      - bash: gem install asciidoctor
        displayName: 'Install asciidoctor'
      - bash: ".azure/scripts/build.sh"
        env:
          BUILD_REASON: $(Build.Reason)
          BRANCH: $(Build.SourceBranch)
          COMMIT: $(Build.SourceVersion)
          DOCKER_USER: $(DOCKER_USER)
          DOCKER_PASS: $(DOCKER_PASS)
          GPG_PASSPHRASE: $(GPG_PASSPHRASE)
          GPG_SIGNING_KEY: $(GPG_SIGNING_KEY)
          NEXUS_USERNAME: $(NEXUS_USERNAME)
          NEXUS_PASSWORD: $(NEXUS_PASSWORD)
          GITHUB_DEPLOY_KEY: $(GITHUB_DEPLOY_KEY)
        displayName: "Build and test"
      - task: PublishTestResults@2
        inputs:
          testResultsFormat: JUnit
          testResultsFiles: '**/TEST-*.xml'
          testRunTitle: "Unit & Integration tests"
        condition: always()
