# Triggers
trigger:
  branches:
    include:
      - 'main'
      - 'release-*'
pr:
  autoCancel: true
  branches:
    include:
      - '*'

# Stages
stages:
  - stage: java_build
    displayName: Java build
    jobs:
      - template: 'templates/jobs/build_java.yaml'
  - stage: docs_build
    displayName: Docs build
    dependsOn: []
    jobs:
      - template: 'templates/jobs/build_docs.yaml'
  - stage: container_build
    displayName: Prepare Container
    dependsOn:
      - java_build
    jobs:
      - template: 'templates/jobs/build_container.yaml'
        parameters:
          artifactSource: 'current'
          artifactProject: 'strimzi'
          artifactPipeline: ''
          artifactRunVersion: ''
          artifactRunId: ''
          architectures: ['amd64', 'arm64']
  - stage: container_publish
    displayName: Publish Container
    dependsOn:
      - container_build
      - docs_build
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
    jobs:
      - template: 'templates/jobs/push_container.yaml'
        parameters:
          dockerTag: 'latest'
          artifactSource: 'current'
          artifactProject: 'strimzi'
          artifactPipeline: ''
          artifactRunVersion: ''
          artifactRunId: ''
          architectures: ['amd64', 'arm64']
  - stage: docs_publish
    displayName: Publish Docs
    dependsOn:
      - container_build
      - docs_build
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
    jobs:
      - template: 'templates/jobs/publish_docs.yaml'
        parameters:
          dockerTag: 'latest'
          artifactSource: 'current'
          artifactProject: 'strimzi'
          artifactPipeline: ''
          artifactRunVersion: ''
          artifactRunId: ''
  - stage: java_deploy
    displayName: Deploy Java
    dependsOn:
      - container_build
      - docs_build
    condition: and(succeeded(), or(eq(variables['build.sourceBranch'], 'refs/heads/main'), startsWith(variables['build.sourceBranch'], 'refs/heads/release-')))
    jobs:
      - template: 'templates/jobs/deploy_java.yaml'
        parameters:
          dockerTag: 'latest'
          artifactSource: 'current'
          artifactProject: 'strimzi'
          artifactPipeline: ''
          artifactRunVersion: ''
          artifactRunId: ''