# Triggers
trigger: none
pr: none

# Parameters
parameters:
- name: releaseVersion
  displayName: Release Version
  type: string
- name: useSuffix
  displayName: Build suffixed images
  type: boolean
  default: true
- name: releaseSuffix
  displayName: Release Suffix
  type: number
- name: sourcePipelineId
  displayName: Pipeline ID of the source build
  type: number
  default: 34
  values:
  - 34
- name: sourceBuildId
  displayName: Build ID of the source build
  type: number

# Stages
stages:
  - stage: containers_publish_with_suffix
    displayName: Publish Containers for ${{ parameters.releaseVersion }}-${{ parameters.releaseSuffix }}
    condition: and(succeeded(), startsWith(variables['build.sourceBranch'], 'refs/heads/release-'))
    jobs:
      - template: 'templates/jobs/push_container.yaml'
        parameters:
          dockerTag: '${{ parameters.releaseVersion }}-${{ parameters.releaseSuffix }}'
          artifactSource: 'specific'
          artifactProject: 'strimzi'
          artifactPipeline: '${{ parameters.sourcePipelineId }}'
          artifactRunVersion: 'specific'
          artifactRunId: '${{ parameters.sourceBuildId }}'
          architectures: ['amd64', 'arm64', 's390x', 'ppc64le']
  - stage: containers_publish
    displayName: Publish Containers for ${{ parameters.releaseVersion }}
    dependsOn:
      - containers_publish_with_suffix
    condition: and(succeeded(), startsWith(variables['build.sourceBranch'], 'refs/heads/release-'))
    jobs:
      - template: 'templates/jobs/push_container.yaml'
        parameters:
          dockerTag: '${{ parameters.releaseVersion }}'
          artifactSource: 'specific'
          artifactProject: 'strimzi'
          artifactPipeline: '${{ parameters.sourcePipelineId }}'
          artifactRunVersion: 'specific'
          artifactRunId: '${{ parameters.sourceBuildId }}'
          architectures: ['amd64', 'arm64', 's390x', 'ppc64le']
