// Module included in the following assemblies:
//
// assembly-kafka-bridge-overview.adoc

[id='con-loggers-kafka-bridge-{context}']

[role="_abstract"]
= Configuring loggers for the Kafka Bridge

[role="_abstract"]
You can set a different log level for each operation that is defined by the Kafka Bridge OpenAPI specification.

Each operation has a corresponding API endpoint through which the bridge receives requests from HTTP clients.
You can change the log level on each endpoint to produce more or less fine-grained logging information about the incoming and outgoing HTTP requests.

Loggers are defined in the `log4j2.properties` file, which has the following default configuration for `healthy` and `ready` endpoints:

```
logger.healthy.name = http.openapi.operation.healthy
logger.healthy.level = WARN
logger.ready.name = http.openapi.operation.ready
logger.ready.level = WARN
```

The log level of all other operations is set to `INFO` by default.
Loggers are formatted as follows:

[source,properties,subs=+quotes]
----
logger._<operation_id>_.name = http.openapi.operation._<operation_id>_
logger._<operation_id>_level = _<LOG_LEVEL>_
----

Where `_<operation_id>_` is the identifier of the specific operation.

.List of operations defined by the OpenAPI specification
* `createConsumer`
* `deleteConsumer`
* `subscribe`
* `unsubscribe`
* `poll`
* `assign`
* `commit`
* `send`
* `sendToPartition`
* `seekToBeginning`
* `seekToEnd`
* `seek`
* `healthy`
* `ready`
* `openapi`

Where _<LOG_LEVEL>_ is the logging level as defined by log4j2 (i.e. `INFO`, `DEBUG`, ...).
