// This assembly is included in the following assemblies:
//
// assembly-http-bridge-overview.adoc

[id='con-securing-http-interface-{context}']
= Securing the HTTP Bridge HTTP interface

[role="_abstract"]
By default, requests sent from clients to the HTTP Bridge are sent without encryption therefore they must use HTTP.
You can configure a TLS-encrypted connection between HTTP clients and the HTTP Bridge through its xref:proc-configuring-kafka-bridge-{context}[properties file].
If the HTTP Bridge is configured with TLS encryption, requests must use HTTPS.

You can enable TLS encryption for all HTTP Bridge endpoints except management endpoints such as `\ready`, `\healthy` and `\metrics`.
These endpoints are typically used only by internal clients and requests to them must use HTTP.

Authentication between HTTP clients and the HTTP Bridge is not supported directly by the HTTP Bridge.
Requests sent from clients to the HTTP Bridge are sent without authentication.

You can combine the HTTP Bridge with the following tools to secure it further:

* Network policies and firewalls that define which pods can access the HTTP Bridge
* Reverse proxies (for example, OAuth 2.0)
* API gateways
