// Module included in the following assemblies:
//
// assembly-kafka-bridge-overview.adoc

[id='con-loggers-kafka-bridge-{context}']

[role="_abstract"]
= Configuring loggers for the Kafka Bridge

The Strimzi Kafka bridge allows you to set a different log level for each operation that is defined by the related OpenAPI specification.

Each operation has a corresponding API endpoint through which the bridge receives requests from HTTP clients.
You can change the log level on each endpoint to produce more or less fine-grained logging information about the incoming and outgoing HTTP requests.

Loggers are defined in the `log4j.properties` file, which has the following default configuration for `healthy` and `ready` endpoints:

```
log4j.logger.http.openapi.operation.healthy=WARN, out
log4j.additivity.http.openapi.operation.healthy=false
log4j.logger.http.openapi.operation.ready=WARN, out
log4j.additivity.http.openapi.operation.ready=false
```

The log level of all other operations is set to `INFO` by default.
Loggers are formatted as follows:

[source,properties,subs=+quotes]
----
log4j.logger.http.openapi.operation._<operation_id>_
----

Where `_<operation_id>_` is the identifier of the specific operation.

.List of operations defined by the OpenAPI specification
* `createConsumer`
* `deleteConsumer`
* `subscribe`
* `unsubscribe`
* `poll`
* `assign`
* `commit`
* `send`
* `sendToPartition`
* `seekToBeginning`
* `seekToEnd`
* `seek`
* `healthy`
* `ready`
* `openapi`
