// Module included in the following assemblies:
//
// assembly-http-bridge-overview.adoc

[id="overview-components-running-http-bridge-{context}"]
= Running the HTTP Bridge

[role="_abstract"]
Install the HTTP Bridge to run in the same environment as your Kafka cluster.

You can download and add the HTTP Bridge installation artifacts to your host machine.
To try out the HTTP Bridge in your local environment, see the xref:assembly-http-bridge-quickstart-{context}[HTTP Bridge quickstart].

[id="overview-components-running-http-bridge-cluster-{context}"]
== Running the HTTP Bridge on Kubernetes

If you deployed Strimzi on Kubernetes, you can use the Strimzi Cluster Operator to deploy the HTTP Bridge to the Kubernetes cluster.
Configure and deploy the HTTP Bridge as a `KafkaBridge` resource.
You'll need a running Kafka cluster that was deployed by the Cluster Operator in a Kubernetes namespace.
You can configure your deployment to access the HTTP Bridge outside the Kubernetes cluster.

Running multiple replicas of the HTTP Bridge in a single Kubernetes `Deployment` is not recommended for consumer workloads. 
Each pod maintains its own consumer state, and pods can be restarted or rescheduled by Kubernetes. 
If the HTTP Bridge pod running a consumer is restarted, the HTTP client must recreate any consumers or subscriptions.

For information on deploying and configuring the HTTP Bridge as a `KafkaBridge` resource, see the {BookURLConfiguring}[Strimzi Custom Resource API Reference^].
