// Module included in the following assemblies:
//
// assembly-kafka-bridge-quickstart.adoc

[id='proc-installing-kafka-bridge-{context}']
= Installing the Kafka Bridge

[role="_abstract"]
Use the script provided with the Kafka Bridge archive to install the Kafka Bridge.
The `application.properties` file provided with the installation archive provides default configuration settings.

The following default property values configure the Kafka Bridge to listen for requests on port 8080.

.Default configuration properties
[source,shell,subs=attributes+]
----
http.enabled=true
http.host=0.0.0.0
http.port=8080
----

.Prerequisites

* xref:proc-downloading-kafka-bridge-{context}[The Kafka Bridge installation archive is downloaded]

.Procedure

. If you have not already done so, unzip the Kafka Bridge installation archive to any directory.

. Run the Kafka Bridge script using the configuration properties as a parameter:
+
For example:
+
[source,shell,subs="+quotes,attributes"]
----
./bin/kafka_bridge_run.sh --config-file=_<path>_/application.properties
----

. Check to see that the installation was successful in the log.
+
[source,shell]
----
HTTP-Kafka Bridge started and listening on port 8080
HTTP-Kafka Bridge bootstrap servers localhost:9092
----

.What to do next

* xref:proc-producing-messages-from-bridge-topics-partitions-{context}[Produce messages to topics and partitions].