// Module included in the following assemblies:
//
// assembly-http-bridge-config.adoc

[id='proc-configuring-http-bridge-{context}']
= Configuring HTTP Bridge properties

[role="_abstract"]
This procedure describes how to configure the Kafka and HTTP connection properties used by the HTTP Bridge.

You configure the HTTP Bridge, as any other Kafka client, using appropriate prefixes for Kafka-related properties.

* `kafka.` for general configuration that applies to producers and consumers, such as server connection and security.
* `kafka.consumer.` for consumer-specific configuration passed only to the consumer.
* `kafka.producer.` for producer-specific configuration passed only to the producer.

As well as enabling HTTP access to a Kafka cluster, HTTP properties provide the capability to enable and define access control for the HTTP Bridge through Cross-Origin Resource Sharing (CORS).
CORS is a HTTP mechanism that allows browser access to selected resources from more than one origin.
To configure CORS, you define a list of allowed resource origins and HTTP methods to access them.
Additional HTTP headers in requests describe the CORS origins that are permitted access to the Kafka cluster.

.Prerequisites

* xref:proc-downloading-http-bridge-{context}[The HTTP Bridge installation archive is downloaded]

.Procedure

. Edit the `application.properties` file provided with the HTTP Bridge installation archive.
+
Use the properties file to specify Kafka and HTTP-related properties.

.. Configure standard Kafka-related properties, including properties specific to the Kafka consumers and producers.
+
Use:
+
* `kafka.bootstrap.servers` to define the host/port connections to the Kafka cluster
* `kafka.producer.acks` to provide acknowledgments to the HTTP client
* `kafka.consumer.auto.offset.reset` to determine how to manage reset of the offset in Kafka
+
For more information on configuration of Kafka properties, see the http://kafka.apache.org[Apache Kafka website^]

.. Configure HTTP-related properties to enable HTTP access to the Kafka cluster.
+
For example:
+
[source,properties]
----
bridge.id=my-bridge
http.host=0.0.0.0
http.port=8080 <1>
http.cors.enabled=true <2>
http.cors.allowedOrigins=https://strimzi.io <3>
http.cors.allowedMethods=GET,POST,PUT,DELETE,OPTIONS,PATCH <4>
----
<1> The default HTTP configuration for the HTTP Bridge to listen on port 8080.
<2> Set to `true` to enable CORS.
<3> Comma-separated list of allowed CORS origins. You can use a URL or a Java regular expression.
<4> Comma-separated list of allowed HTTP methods for CORS.
+
Or configure HTTP-related properties to enable TLS-encryption between clients and HTTP Bridge.
+
For example:
+
[source,properties]
----
bridge.id=my-bridge
http.host=0.0.0.0
http.port=8443 <5>
http.ssl.enable=true <6>
http.ssl.certificate.location=/etc/ssl/certs/bridge.crt <7>
http.ssl.key.location=/etc/ssl/private/bridge.key <8>
----
<5> Configure HTTP Bridge to listen on port 8443 for TLS encrypted connections.
<6> Set `true` to enable TLS encryption between HTTP clients and the HTTP Bridge.
<7> Location of the certificate file in PEM format.
<8> Location of the private key file in PEM format.

. Save the configuration file.

.HTTP related configurations
|====
|Name |Descriptions

|http.host
|HTTP Bridge host address. The default is `0.0.0.0`.

|http.port
|HTTP Bridge port. The default is `8080`. If "http.ssl.enable" is set to `true`, then the default is `8443`.

|http.management.port
|HTTP bridge port for management endpoints such as `/healthy`, `/ready` and `/metrics`. The default is `8081`.

|http.ssl.enable
|Enable TLS encryption between HTTP clients and HTTP bridge. It is `false` by default.
If set to `true`, `http.ssl.certificate.location` and `http.ssl.key.location` configurations or
 `http.ssl.certificate` and `http.ssl.key` configurations are required.

|http.ssl.certificate.location
|The location of the HTTP Bridge server certificate file in PEM format.
PEM is the only format supported for certificate.

|http.ssl.key.location
|The location of the HTTP Bridge server private key file in PEM format.
PEM is the only format supported for private key.

|http.ssl.certificate
|The HTTP Bridge server certificate in PEM format.
PEM is the only format supported for certificate.

|http.ssl.key
|The HTTP Bridge server private key in PEM format.
PEM is the only format supported for private key.

|http.ssl.enabled.protocols
|Comma-separated list of protocols enabled for TLS connections. `TLSv1.2,TLSv1.3` is the default.

|http.ssl.enabled.cipher.suites
|Comma-separated list of cipher suites. The default of the underlying JVM version is used.

|http.cors.enabled
|Enable CORS. The default is `false`.

|http.cors.allowedOrigins
|Comma-separated list of allowed CORS origins. You can use a URL or a Java regular expression.

|http.cors.allowedMethods
|Comma-separated list of allowed HTTP methods for CORS.

|http.consumer.enabled
|Enable consumer part of the HTTP Bridge. The default is `true`.

|http.producer.enabled
|Enable producer part of the HTTP Bridge. The default is `true`.

|http.timeoutSeconds
|The timeout for closing inactive consumer. By default, inactive consumers will not be closed.
|====