// Module included in the following assemblies:
//
// assembly-http-bridge-quickstart.adoc

[id='proc-installing-http-bridge-{context}']
= Installing the HTTP Bridge

[role="_abstract"]
Use the script provided with the HTTP Bridge archive to install the HTTP Bridge.
The `application.properties` file provided with the installation archive provides default configuration settings.

The following default property values configure the HTTP Bridge to listen for requests on port 8080.

.Default configuration properties
[source,shell,subs=attributes+]
----
http.host=0.0.0.0
http.port=8080
----

.Prerequisites

* xref:proc-downloading-http-bridge-{context}[The HTTP Bridge installation archive is downloaded]

.Procedure

. If you have not already done so, unzip the HTTP Bridge installation archive to any directory.

. Run the HTTP Bridge script using the configuration properties as a parameter:
+
For example:
+
[source,shell,subs="+quotes,attributes"]
----
./bin/kafka_bridge_run.sh --config-file=_<path>_/application.properties
----

. Check to see that the installation was successful in the log.
+
[source,shell]
----
HTTP Bridge started and listening on port 8080
HTTP Bridge bootstrap servers localhost:9092
----

.What to do next

* xref:proc-producing-messages-from-bridge-topics-partitions-{context}[Produce messages to topics and partitions].