name: Build

on:
  push:
    branches:
      - "main"
      - "release-*"
  pull_request:
    branches:
      - "*"

# Declare default permissions as read only
permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-kafka-bridge:
    name: Build Kafka Bridge
    strategy:
      matrix:
        # Java 21 is used as default version
        # In case of adding new version make sure that build-containers and deploy-java has correct static version set
        java:
          - version: "21"
            mainBuild: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Java and Maven
        uses: strimzi/github-actions/.github/actions/dependencies/setup-java@v1
        with:
          javaVersion: ${{ matrix.java.version }}

      - name: Build binaries using build-binaries action
        uses: strimzi/github-actions/.github/actions/build/build-binaries@v1
        with:
          mainJavaBuild: ${{ matrix.java.mainBuild }}
          artifactSuffix: "kafka-bridge"

  build-docs:
    name: Build docs
    needs:
      - build-kafka-bridge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/build/build-docs
        with:
          artifactName: "documentation.tar"
          runnerArch: "amd64"

  build-containers:
    name: Build Containers
    needs:
      - build-kafka-bridge
    strategy:
      matrix:
        architecture:
          - amd64
          - arm64
          - s390x
          - ppc64le
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: strimzi/github-actions/.github/actions/dependencies/install-docker@v1

      - uses: strimzi/github-actions/.github/actions/build/build-containers@v1
        with:
          architecture: ${{ matrix.architecture }}
          artifactSuffix: "kafka-bridge"
          containerRegistry: "quay.io"
          containerOrg: "strimzi"
          containerTag: "latest"
          imagesDir: "kafka-bridge-${{ matrix.architecture }}.tar.gz"

  push-containers:
    name: Push Containers
    needs:
      - build-kafka-bridge
      - build-containers
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6

      - uses: strimzi/github-actions/.github/actions/dependencies/install-docker@v1

      - uses: strimzi/github-actions/.github/actions/dependencies/install-syft@v1

      - uses: strimzi/github-actions/.github/actions/build/push-containers@v1
        with:
          architectures: "amd64,arm64,ppc64le,s390x"
          containerRegistry: "quay.io"
          containerOrg: "strimzi"
          containerTag: "latest"
          registryUser: ${{ secrets.QUAY_USER }}
          registryPassword: ${{ secrets.QUAY_PASS }}
          artifactSuffix: "kafka-bridge"

  publish-docs:
    name: Publish Docs
    needs:
      - build-kafka-bridge
      - build-containers
      - build-docs
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/build/publish-docs
        with:
          artifactName: "documentation.tar"
          websiteDeployKey: ${{ secrets.WEBSITE_DEPLOY_KEY }}

  deploy-java:
    name: Deploy Java artifacts
    needs:
      - build-kafka-bridge
      - build-containers
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: strimzi/github-actions/.github/actions/dependencies/setup-java@v1
        with:
          javaVersion: "21"

      - uses: strimzi/github-actions/.github/actions/build/deploy-java@v1
        with:
          gpgPassphrase: ${{ secrets.GPG_PASSPHRASE }}
          gpgSigningKey: ${{ secrets.GPG_SIGNING_KEY }}
          centralUsername: ${{ secrets.CENTRAL_USERNAME }}
          centralPassword: ${{ secrets.CENTRAL_PASSWORD }}
          artifactSuffix: "kafka-bridge"
          modules: "./"