name: GitHub Actions Integration

on:
  pull_request:
    paths:
      - 'pom.xml'
      - 'Dockerfile'
      - 'Makefile'
      - 'Makefile.common'
      - 'Makefile.docker'
      - 'Makefile.maven'
      - 'Makefile.os'
      - '.github/workflows/github-actions-integration.yml'
    branches:
      - "*"

permissions:
  contents: read
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-github-actions-integration:
    uses: strimzi/github-actions/.github/workflows/reusable-test-integrations.yml@52b17c19f3687e37b47c9c64696b96f28f53625b # v2.3
    with:
      repo: ${{ github.repository }}
      ref: ${{ github.sha }}
      architecture: "amd64"
      artifactSuffix: "kafka-bridge"
      buildContainers: true
      modules: "./"
      nexusCheck: "kafka-bridge"
      javaVersion: "21"
      helmChartName: "none"
      releaseVersion: "6.6.6"
      imagesLocation: "kafka-bridge-amd64.tar.gz"
      githubActionsRef: "v2.3"
    secrets: inherit